// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuInn1LvooDjuzpAhqXAkUeC7k7ET26-A',
    appId: '1:429478821172:web:34a9521b2041f3956e3961',
    messagingSenderId: '429478821172',
    projectId: 'wafarha-2bf77',
    authDomain: 'wafarha-2bf77.firebaseapp.com',
    databaseURL: 'https://wafarha-2bf77-default-rtdb.firebaseio.com',
    storageBucket: 'wafarha-2bf77.appspot.com',
    measurementId: 'G-JF76WHY8GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlTTWfxgTBDC7ckX2H2rKpOQo-6enpDKQ',
    appId: '1:429478821172:android:10d80aba7227dd286e3961',
    messagingSenderId: '429478821172',
    projectId: 'wafarha-2bf77',
    databaseURL: 'https://wafarha-2bf77-default-rtdb.firebaseio.com',
    storageBucket: 'wafarha-2bf77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-k3iHU_gbzmNnnjnDYawt0boIT8kQerI',
    appId: '1:429478821172:ios:c570dca34c674c606e3961',
    messagingSenderId: '429478821172',
    projectId: 'wafarha-2bf77',
    databaseURL: 'https://wafarha-2bf77-default-rtdb.firebaseio.com',
    storageBucket: 'wafarha-2bf77.appspot.com',
    iosClientId: '429478821172-0cnmknqt6aug2s8nhks1l5keq8usci5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpandaSeller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-k3iHU_gbzmNnnjnDYawt0boIT8kQerI',
    appId: '1:429478821172:ios:c570dca34c674c606e3961',
    messagingSenderId: '429478821172',
    projectId: 'wafarha-2bf77',
    databaseURL: 'https://wafarha-2bf77-default-rtdb.firebaseio.com',
    storageBucket: 'wafarha-2bf77.appspot.com',
    iosClientId: '429478821172-0cnmknqt6aug2s8nhks1l5keq8usci5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpandaSeller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuInn1LvooDjuzpAhqXAkUeC7k7ET26-A',
    appId: '1:429478821172:web:34a9521b2041f3956e3961',
    messagingSenderId: '429478821172',
    projectId: 'wafarha-2bf77',
    authDomain: 'wafarha-2bf77.firebaseapp.com',
    databaseURL: 'https://wafarha-2bf77-default-rtdb.firebaseio.com',
    storageBucket: 'wafarha-2bf77.appspot.com',
    measurementId: 'G-JF76WHY8GC',
  );
}
